### ISSUE TITLE
Crashing during gameplay

### ISSUE THREAD

**Issue by Liquid5n0w** [walkco/stadia-vigem#5]
Hey I have been using stadia-vigem for a while, and now stadia-vigem has started crashing halfway through gameplay. Controllers stop responding and when I open the tray icon it disappears. What's going on?

I tried looking for an update, but the last version was from 2020?

I suspect it's me and not your software, 

Here is the vigem dmp file:
https://drive.google.com/file/d/1Ti8Is-jrgwIIYZmbuiGT5ztz7cq2N6Xa/view?usp=sharing

**Comment by walkco** [comment]
Hi @Liquid5n0w, I've just published a new version which has fixes for issues that I've discovered since the initial release, could you try it and let me know if it resolves your issue?

If it doesn't, unfortunately, free time for me to work on this can be rare but when I do have some time, I'll look into it.

**Comment by Liquid5n0w** [comment]
I'll check the new update out now, thanks! I played for about 4 hours today without issue using 2 stadia controllers. I changed nothing from when it was crashing, so I suspect a random root cause.
